### ISSUE TITLE
Origa Mito

### ISSUE THREAD

**Issue by Omito** [mmagnuski/Biology-of-Brain-and-Behavior#10]
Topic: Prefrontal Cortex
http://en.wikipedia.org/wiki/Prefrontal_cortex

**Comment by Omito** [comment]
Origa Mito
Topic: Prefrontal Cortex
1) http://en.wikipedia.org/wiki/Prefrontal_cortex
2) http://www.sciencedaily.com/releases/2014/08/140828135517.htm

**Comment by mmagnuski** [comment]
Hey, it will be much clearer if you post this in the original thread - Homework - papers.
I might have not been clear enough on our last meeting - your homeworks should go into one issue (the one I created).
BTW - wikipedia article is not a scientific publication (although its good to learn from) :smile:

**Comment by mmagnuski** [comment]
Ah, good, you have posted there already.

**Comment by Omito** [comment]
Origa Mito 
Third try.
1) How studying damage to prefrontal cortex
http://www.sciencedaily.com/releases/2014/08/140828135517.htm
2) Brain frontal lobe not sole center of human intelligence
http://www.sciencedaily.com/releases/2013/05/130513152827.htm
