### ISSUE TITLE
Project Ana & Laura

### ISSUE THREAD

**Issue by anaortiztallo** [mmagnuski/Biology-of-Brain-and-Behavior#13]
Neural Mechanisms of depression

Laura Gonzalez Vives 0552G
Ana Ortiz-Tallo Moya 0574G

Starting Bibliography:

Auerbach, Randy P. et al. (2013), Behavioral and neural mechanisms underlying cognitive vulnerability models of depression. Journal of Psychotherapy Integration,23(3). 10.1179/1476830514Y.0000000115

Kaiser, RH. Et al. (2015) Distracted and down: neural mechanisms of affective interference in subclinical depression. Social cognitive and affective neuroscience, 10(5).10.1093/scan/nsu100

Foland-Ross, Lara C. et al. (2015). Neural Markers of Familial Risk for Depression: An Investigation of Cortical Thickness Abnormalities in Healthy Adolescent Daughters of Mothers With Recurrent Depression. Journal of Abnormal Psychology. 10.1037/abn0000050

Paul, Natalie A.(2013). Psychological and neural mechanisms of trait mindfulness in reducing depression vulnerability. Social cognitive and affective neuroscience,8(1).

Wang, N. et al. (2013). Brain-network mechanisms underlying the divergent effects of depression on spontaneous versus evoked pain in rats: a multiple single-unit study. Experimental Neurology, 250.10.1016/j.expneurol.2013.09.021

Fung, J. (2015). Association of decreased serum brain-derived neurotrophic factor (BDNF) concentrations in early pregnancy with antepartum depression. BMC Psychiatry 15(1). 10.1186/s12888-015-0428-7

**Comment by mmagnuski** [comment]
Good, I will be sending more specific feedback this week. Tommorrow I will also let you know when and where you can find me in case of consultations etc.
