### ISSUE TITLE
Project Ana & Laura

### ISSUE THREAD

**Issue by anaortiztallo** [mmagnuski/Biology-of-Brain-and-Behavior#14]
Neural Mechanisms of depression

Laura Gonzalez Vives 0552G
Ana Ortiz-Tallo Moya 0574G

Starting Bibliography:

Auerbach, Randy P. et al. (2013), Behavioral and neural mechanisms underlying cognitive vulnerability models of depression. Journal of Psychotherapy Integration,23(3). 10.1179/1476830514Y.0000000115
Kaiser, RH. Et al. (2015) Distracted and down: neural mechanisms of affective interference in subclinical depression. Social cognitive and affective neuroscience, 10(5).10.1093/scan/nsu100
Foland-Ross, Lara C. et al. (2015). Neural Markers of Familial Risk for Depression: An Investigation of Cortical Thickness Abnormalities in Healthy Adolescent Daughters of Mothers With Recurrent Depression. Journal of Abnormal Psychology. 10.1037/abn0000050
Paul, Natalie A. et al.(2013). Psychological and neural mechanisms of trait mindfulness in reducing depression vulnerability. Social cognitive and affective neuroscience,8(1).
Wang, N. et al. (2013). Brain-network mechanisms underlying the divergent effects of depression on spontaneous versus evoked pain in rats: a multiple single-unit study. Experimental Neurology, 250.10.1016/j.expneurol.2013.09.021
Fung, J. (2015). Association of decreased serum brain-derived neurotrophic factor (BDNF) concentrations in early pregnancy with antepartum depression. BMC Psychiatry 15(1). 10.1186/s12888-015-0428-7
http://www.health.harvard.edu/mind-and-mood/what-causes-depression
http://www.allaboutdepression.com/cau_03.html

Depression and brain anatomy

Brain parts related to depression:

Amygdala: The amigdala is a part of the limbic system that is quite related to depression. Amygdala is the responsible brain part of emotions such as anger, pleasure, sorrow, fear and sex arousal. The amygdala is activated when a person recalls emotionally charged memories, such as a frightening situation. Activity in the amygdala is higher when a person is sad or clinically depressed. This increased activity continues even after recovery from depression.
Thalamus: The thalamus receives most sensory information and relays it to the appropriate part of the cerebral cortex, which directs high-level functions such as speech, behavioral reactions, movement, thinking, and learning. Some research suggests that bipolar disorder may result from problems in the thalamus, which helps link sensory input to pleasant and unpleasant feelings.
Hippocampus: The hippocampus is part of the limbic system and has a central role in processing long-term memory and recollection. Interplay between the hippocampus and the amygdala might account for the adage “once bitten, twice shy.” It is this part of the brain that registers fear when you are confronted by a barking, aggressive dog, and the memory of such an experience may make you wary of dogs you come across later in life. The hippocampus is smaller in some depressed people, and research suggests that ongoing exposure to stress hormone impairs the growth of nerve cells in this part of the brain.

Neurotransmitters related to depression

Scientists have identified many different neurotransmitters. Here is a description of a few believed to play a role in depression:
• Acetylcholine enhances memory and is involved in learning and recall.
• Serotonin helps regulate sleep, appetite, and mood and inhibits pain. Research supports the idea that some depressed people have reduced serotonin transmission. Low levels of a serotonin byproduct have been linked to a higher risk for suicide.
• Norepinephrine constricts blood vessels, raising blood pressure. It may trigger anxiety and be involved in some types of depression. It also seems to help determine motivation and reward.
• Dopamine is essential to movement. It also influences motivation and plays a role in how a person perceives reality. Problems in dopamine transmission have been associated with psychosis, a severe form of distorted thinking characterized by hallucinations or delusions. It’s also involved in the brain’s reward system, so it is thought to play a role in substance abuse.
• Glutamate is a small molecule believed to act as an excitatory neurotransmitter and to play a role in bipolar disorder and schizophrenia. Lithium carbonate, a well-known mood stabilizer used to treat bipolar disorder, helps prevent damage to neurons in the brains of rats exposed to high levels of glutamate. Other animal research suggests that lithium might stabilize glutamate reuptake, a mechanism that may explain how the drug smooths out the highs of mania and the lows of depression in the long term.
• Gamma-aminobutyric acid (GABA) is an amino acid that researchers believe acts as an inhibitory neurotransmitter. It is thought to help quell anxiety.

GENES

It has been found that when one identical twin becomes depressed the other will also develop clinical depression approximately 76% of the time. When identical twins are raised apart from each other, they will both become depressed about 67% of the time. Because both twins become depressed at such a high rate, the implication is that there is a strong genetic influence. If it happened that when one twin becomes clinically depressed the other always develops depression, then clinical depression would likely be entirely genetic. However because the rate of both identical twins developing depression is not closer to 100% this tells us that there are other things that influence a person's vulnerability to depression. These may include environmental factors such as childhood experiences, current stressors, traumatic events, exposure to substances, medical illnesses, etc.
People with a particular variant in a serotonin-transporter gene (5-HTT) were more likely to become depressed in response to stress. 
Another interesting discovery is the identification of a variation in the DNA sequence named G1463A. People with this atypical DNA sequence are more likely to have major depression than those who don’t.

Other findings:

According to Paul, Natalie A. et al.(2013) study in which they examined which facets of trait mindfulness offer protection against negative bias and rumination, which are key risk factors for depression. 
Non-reactivity was negatively correlated with activation in the left anterior insula during inhibiting and engaging in negative stimuli after the mindful breathing task, whereas rumination was positively correlated with activation in bilateral anterior insula activation after the stress task. These findings indicate that trait non-reactivity is a critical component of mindfulness that could protect against negative bias by reducing automatic emotional responding to negative stimuli reflected by reduced anterior insula activation under stress. Taken together, the data suggest plausible psychological and neural mechanisms that could explain how a specific facet of mindfulness—non-reactivity to negative stimuli—might buffer vulnerability to depression.
There are studies which have found greater cortical thickness in meditators compared with non-meditators in the right insula (Lazar et al., 2005; Hölzel et al., 2008) and other regions. Using different cognitive and affective paradigms, increased and decreased insular activation has also found to be associated with dispositional mindfulness or post-intervention mindfulness

According to Fung, J. et al. (2015), maternal early pregnancy serum BDNF levels were significantly lower in women with antepartum depression compared to women without depression  Lower BDNF 
levels were associated with increased odds of maternal antepartum depression. 
Lower maternal serum BDNF levels in early pregnancy are associated with antepartum depression. These findings may point toward new therapeutic opportunities and BDNF should be assessed as a potential biomarker for risk prediction and monitoring response to treatment for antepartum depression.

Theories (depression): 
(a) Beck’s cognitive model of depression, 
(b) hopelessness theory of depression.
(c) response styles theory.
In these theories behavioural and neurobiological mechanisms play an important rol to create or influence vulnerability factors. The aim of this article is to correlate cognitive vulnerability factors in depression and recommendations relates to etiology and treatment.
Beck
-Functional neuroimaging studies have reported increased amygdala activation in response to negative emotional stimuli in depressed individuals relative to healthy controls (Surguladze et al., 2005; Sheline et al., 2001; Siegle, Steinhauer, Thase, Stenger, & Carter, 2002; Siegle, Thompson, Carter, Steinhauer, & Thase, 2007).
-Sheline et al. (2001) observed increased amygdala activation to fearful faces among depressed, relative to never-depressed, participants even when stimuli were presented outside of conscious awareness. In addition, studies have found that amygdala hyperarousal within depressed individuals persists even after the negative emotional stimuli are no longer present (Siegle et al., 2002; 2007).
-Negative cognitions about the future have been linked to amygdala reactivity.  Specifically, even the expectation of aversive stimuli elicits greater activation in sublenticular extended dorsal amygdala of depressed patients relative to controls (Abler, Erk, Herwig, & Walter, 2007). 
-Related findings on increased amygdala reactivity to negative emotional stimuli are studies reporting decreased activation in ventral striatal regions in response to positive stimuli in depression
-Similarly, studies using electroencephalography (EEG) have reported reduced feedback-related positivity (FRP)—a frontocentral waveform hypothesized to originate from dorsal anterior cingulate cortex (dACC) and striatal regions—in response to reward
-Hypoactivity in prefrontal cortex (PFC) regions, including the dorsolateral prefrontal (DLPFC), have also been linked to depressive symptoms.Researchers identified promising neurobiological substrates that may underlie helplessness.
Hopelessness theory of depression: Research has indicated that depressed individuals exhibit relatively reduced left frontal activation as compared to non-depressed individuals (for review see Davidson, Pizzagalli, & Nitschke, 2002). 

Depressive symptoms predicted increased activation to negative distractors in areas of dorsal anterior cingulate cortex (dACC) and posterior cingulate cortex (PCC), regions implicated in cognitive control and internally directed attention, respectively. Increased dACC activity was also observed in the group-average response to incongruent distractors, suggesting that dACC activity during affective interference is related to overtaxed cognitive control. In contrast, regions of PCC were deactivated across the group in response to incongruent distractors, suggesting that PCC activity during affective interference represents task-independent processing. 

Having a mother with major depressive disorder (MDD) is one of the strongest predictors of depression in late adolescence and early adulthood. Despite this fact, we know little about the neural mechanisms involved in the intergenerational transmission of risk for depression. 
Scan data were processed to provide measurements of cortical gray matter thickness. Children’s Sadness Management Scale, indicated that thinner gray matter in the ACC of high-risk girls was associated with greater difficulty in managing sadness
-The most robust structural changes in MDD involve reductions in gray matter in the anterior cingulate cortex.
- The dorsolateral and orbitofrontal prefrontal cortex (Bora et al., 2012), are more pronounced in individuals who have experienced several depressive episodes
- Moreover, structural abnormalities in this region and in other brain regions that have been found to be characterized by reduced gray matter in MDD, such as the dorsolateral and orbitofrontal prefrontal cortex (Bora et al., 2012), are more pronounced in individuals who have experienced several depressive episodes-

**Comment by mmagnuski** [comment]
Cool, I will try to read and check it and give you feedback before thursday.

**Comment by mmagnuski** [comment]
Oops, sorry, I forgot about this post. I will extend the deadline for all those that did not receive feedback on time. I will give you feedback today.

**Comment by mmagnuski** [comment]
This work was graded by e-mail :)
