### ISSUE TITLE
Homework - papers

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/Biology-of-Brain-and-Behavior#7]
amygdala and trustworthiess
http://psych.nyu.edu/freemanlab/pubs/2014Freeman_JNeuro.pdf
another paper here!

**Comment by mmagnuski** [comment]
Mikołaj Magnuski
topic here
paper one here
paper two here

**Comment by mmagnuski** [comment]
Mikołaj Magnuski
random stuff
- Kristen Delevich, Jason Tucciarone, Z. Josh Huang, and Bo Li. The Mediodorsal Thalamus Drives Feedforward Inhibition in the Anterior Cingulate Cortex via Parvalbumin Interneurons. The Journal of Neuroscience, April 2015
- http://psych.nyu.edu/freemanlab/pubs/2014Freeman_JNeuro.pdf

**Comment by ioannisstam25** [comment]
Ioannis Stamatelos

1)The neural correlates of justified and unjustified killing: An fMRI study: 
http://www.sciencedaily.com/releases/2015/04/150408100651.htm

2)Relationship between exploratory eye movements and brain
morphology in schizophrenia spectrum patients: 
http://web.b.ebscohost.com/ehost/pdfviewer/pdfviewer?vid=43&sid=e02150df-9e5e-46ac-9bf7-9d843e930b38%40sessionmgr111&hid=109

**Comment by JedrzejNowe** [comment]
Jędrzej Nowe

1) Planning and spatial working memory following frontal lobe lesions in man
http://owenlab.uwo.ca/pdf/1990-Owen-Neuropsychologia-PLANNING%20AND%20SPATIAL%20WORKING%20MEMORY%20FOLLOWING%20FRONTAL%20LOBE%20LESIONS%20IN%20MAN.pdf

2) Differential Contribution of Amygdala and Hippocampus to Cued and Contextual Fear Conditioning
http://www.morganparkcps.org/ourpages/auto/2011/4/5/50843958/PhillipsR1992a.pdf

**Comment by SashaBitova** [comment]
Oleksandra Bitova

1) New hope for Alzheimer's: Meds already in use for stroke in some Asian countries
http://www.sciencedaily.com/releases/2015/04/150407212948.htm

2) Discovery of communication link between brain areas implicated in schizophrenia
http://www.sciencedaily.com/releases/2015/04/150407210901.htm

**Comment by ugurck** [comment]
Ugur Can Koc

1)A developmental and genetic classification for midbrain-hindbrain malformations.
http://brain.oxfordjournals.org/content/brain/132/12/3199.full.pdf

2) Neurological diseases share common blood-brain barrier defects.The findings could yield new approaches for treating brain diseases.
http://www.sciencedaily.com/releases/2015/03/150330173827.htm

**Comment by Alexandra17** [comment]
Oleksandra Chyzhevska 
1) No evidence that low-frequency magnetic fields accelerate development of Alzheimer's disease and ALS
http://www.sciencedaily.com/releases/2015/04/150407084902.htm
2) Cerebral curiosity leads to discovery
http://www.sciencedaily.com/releases/2015/04/150407095352.htm

**Comment by dkremen** [comment]
Darya Kremen
The Brain & Bilingualism

1) The effects of bilingualism on the white matter structure of the brain:
http://www.pnas.org/content/112/5/1334.full.pdf
2) Event-related brain potential investigation of preparation for speech production in late bilinguals:
http://journal.frontiersin.org/article/10.3389/fpsyg.2011.00114/full

**Comment by maryanisabi** [comment]
Marianna Capuani...sorry!!! Here they are:-)

The bilingual brain

1) Language control in the bilingual brain
http://brl.psy.univie.ac.at/uploads/silani/BiologischePsychologie2010/CH16_add%20reading2.pdf

2) Dissociating language and word meaning in the bilingual brain
http://www.cogneuro-lab.org/UserFiles/Publication/Dissociatinglanguageandwordmeaninginthebilingualbrain_TrendsinCogSci2006.pdf

**Comment by Omito** [comment]
Origa Mito

Prefrontal Cortex

1) Detailed explanation of  the Prefrontal Cortex
    http://en.wikipedia.org/wiki/Prefrontal_cortex

2) How studying damage to prefrontal lobe has helped unlock the brain's mysteries
    http://www.sciencedaily.com/releases/2014/08/140828135517.htm

**Comment by mmagnuski** [comment]
@maryanisabi : you have posted links to files on your computer. Unfortunatelly, I cannot access these :) Please post links to internet resources (pdf or journal page with abstract of the paper).

**Comment by hergin8** [comment]
Hale ERGIN 

1) recalling memories make us forget
http://scitechconnect.elsevier.com/recalling-memories/
2) Electrical stimulation 'tunes' visual attention
http://www.sciencedaily.com/releases/2015/01/150114090817.htm

**Comment by kbrkcc** [comment]
Kubra KECECI

1-Controlling Self-Awareness During Sleep

http://www.the-scientist.com/?articles.view/articleNo/39939/title/Controlling-Self-Awareness-During-Sleep/

2-Molecular trigger found for schizophrenia-like behaviors, brain changes

http://www.sciencedaily.com/releases/2015/04/150407152330.htm

**Comment by Omito** [comment]
Thank you Mikolaj for comments.

Second try. :)

Origa Mito

Topic: Prefrontal cortex

1) Global connectivity of prefrontal cortex predicts cognitive control and intelligence
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3392686/

2) The role of prefrontal cortex in working-memory capacity
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3392686/

**Comment by 1c3m0nkey** [comment]
Tomasz Weiss

1) - Focused ultrasound: crossing barriers to treat Alzheimer’s disease
http://www.future-science.com/doi/pdfplus/10.4155/tde.11.5?src=recsys& 

2) - Feasibility of Transcranial, Localized Drug-delivery in the Brain of Alzheimer′s-model Mice Using Focused Ultrasound
http://orion.bme.columbia.edu/ueil/documents/inproceedings/2005-choi-bbb-alzheimer-mice.pdf

**Comment by daryna1** [comment]
Daryna Chadiuk

1) Secrets of the brain
http://ngm.nationalgeographic.com/2014/02/brain/zimmer-text

2)Study finds it's possible to train the brain to choose healthier food over junk food
http://www.naturalnews.com/047673_brain_health_junk_food_healthy_eating.html

**Comment by Tubakasaboglu** [comment]
Tuba Kasaboglu

1- Music listening while you learn: No influence of background music on verbal learning ;
http://www.behavioralandbrainfunctions.com/content/6/1/3

2-Relationship between abstract thinking and eye gaze pattern in patients with schizophrenia ;
http://www.behavioralandbrainfunctions.com/content/10/1/13

**Comment by Emrullah571** [comment]
Emrullah Beydogan

1) Sleep difficulties may be linked to faster rates of decline in brain volume ... 

http://www.sciencedaily.com/releases/2014/09/140903161600.htm

2) Dysfunctional activation and brain network profiles in youth with obsessive-compulsive disorder: a focus on the dorsal anterior cingulate during working memory

http://journal.frontiersin.org/article/10.3389/fnhum.2015.00149/full

**Comment by ecemcoskun** [comment]
Ecem Coskun 
1)The roles of interoceptive sensitivity and metacognitive interoception in panic
http://www.behavioralandbrainfunctions.com/content/11/1/14/abstract
2)Anxiolytic and antidepressant profile of the methanolic extract of Piper nigrum fruits in beta-amyloid (1–42) rat model of Alzheimer’s disease
http://www.behavioralandbrainfunctions.com/content/11/1/13

**Comment by suYildiz** [comment]
Berfin Su Yıldız  

1 - A differential neural response in the human amygdala to fearful and happy facial expressions 
http://www.nature.com/nature/journal/v383/n6603/abs/383812a0.html

2- The Role of the Amygdala in Fear and Anxiety
http://www.annualreviews.org/doi/abs/10.1146/annurev.ne.15.030192.002033?journalCode=neuro

**Comment by Hale-Bayatli** [comment]
Hale Bayatli

1 ) THE WHOLE BRAIN CHILD BY SIEGEL AND BRYSON
http://www.exampleessays.com/viewpaper/203423.html

2)LEARNING AS BIOLOGICAL BRAIN CHANGE
http://www.exampleessays.com/viewpaper/34848.html

3)What causes depression?
http://www.health.harvard.edu/mind-and-mood/what-causes-depression

4)11 Toxic Chemicals Affecting Brain Development In Children
http://www.forbes.com/sites/alicegwalton/2014/02/15/11-toxic-chemicals-afffecting-brain-development-in-children/

5)Language and Brain,Neurocognitive Linguistics
http://www.ruf.rice.edu/~lngbrain/main.htm

**Comment by mariasoosai** [comment]
Maria R. Soosai
1) Brain activity in infants predicts language outcomes in autism spectrum disorder.
http://www.sciencedaily.com/releases/2015/04/150409133413.htm

2) The brain game: How decreased neural activity may help you learn faster.
http://www.sciencedaily.com/releases/2015/04/150406121348.htm

**Comment by salomedvali** [comment]
1)Brain benefits from weight loss following bariatric surgery

http://www.sciencedaily.com/releases/2014/08/140826141128.htm

2) Amygdala Response to Happy Faces as a Function of Extraversion
http://qglw.personality-project.org/revelle/syllabi/classreadings/canli.pdf

**Comment by salomedvali** [comment]
The role of the Amigdala in Fair and anxiety
1)http://www.annualreviews.org/doi/abs/10.1146/annurev.ne.15.030192.002033?journalCode=neuro

2)Antisocial personality disorder, childhood delinquency, and frontal brain functioning: EEG and neuropsychological findings
http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-4679(199611)52:6%3C639::AID-JCLP6%3E3.0.CO;2-F/abstract;jsessionid=2DB6973158472BB3DD5868DE6051FC5F.f04t04

**Comment by martakuczynska** [comment]
Marta Kuczyńska
1. The Tipping Point of Animacy: How, When, and Where We Perceive Life in a Face http://media.virbcdn.com/files/ae/FileItem-181443-LooserWheatley2010.pdf

2. Early Musical Training and White-Matter Plasticity in the Corpus Callosum: Evidence for a Sensitive Period   http://www.jneurosci.org/content/33/3/1282.full.pdf

**Comment by martakuczynska** [comment]
Marta Kuczyńska
1. The Tipping Point of Animacy: How,When, and Where We Perceive Life in a Face http://media.virbcdn.com/files/ae/FileItem-181443-LooserWheatley2010.pdf

2. Early Musical Training and White-Matter Plasticity in the Corpus Callosum: Evidence for a Sensitive Period http://www.jneurosci.org/content/33/3/1282.full.pdf

**Comment by martakuczynska** [comment]
Marta Kuczyńska
1) The Tipping Point of Animacy: How,When, and Where We Perceive Life in a Face http://media.virbcdn.com/files/ae/FileItem-181443-LooserWheatley2010.pdf

2) Early Musical Training and White-Matter Plasticity in the Corpus Callosum: Evidence for a Sensitive Period 
 http://www.jneurosci.org/content/33/3/1282.full.pdf

**Comment by NastyaTeterina** [comment]
Anastasiia Teterina
1)Brain Facts
http://www.brainhq.com/brain-resources/brain-facts-myths/brain-facts
2)BRAIN TUMORS
http://braintumor.org/brain-tumor-information/understanding-brain-tumors/

**Comment by janbankowski** [comment]
Jan Bańkowski
1) PET imaging reveals brain functional changes in internet gaming disorder. 
http://web.a.ebscohost.com/ehost/detail/detail?sid=529d75b3-f8dd-4941-bd74-ab0985c1bc3c%40sessionmgr4002&vid=0&hid=4114&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#db=a9h&AN=96409608

2) Exercise Benefits Brain Function: The Monoamine Connection. 
http://web.a.ebscohost.com/ehost/detail/detail?sid=b3b9bc68-8641-443d-b0a5-0aa6fb4e5f28%40sessionmgr4001&vid=0&hid=4114&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#db=a9h&AN=86682859

**Comment by YulieTK** [comment]
Yuliia Tkachuk
1) The neurobiology of addiction.
http://www.cogsci.ucsd.edu/~pineda/COGS260/addiction/neurobiology%20of%20addiction.pdf

2) The neurobiology of pleasure, reward processes, addiction and their health implications.
http://www.nel.edu/pdf_/NEL250404R01_Esch-Stefano_p_.pdf

**Comment by GuShengyin** [comment]
Gu Shengyin
(1)Persistent Insomnia is Associated with Mortality Risk
https://scholar.google.com.hk/scholar?q=Persistent+Insomnia+is+Associated+with+Mortality+Risk&hl=en&as_sdt=0&as_vis=1&oi=scholart&sa=X&ei=EDApVY-WBY7-aNaygIgB&ved=0CBgQgQMwAA

(2)The brain game: How decreased neural activity may help you learn faster
http://scholar.google.pl/scholar_url?url=http%3A%2F%2Farxiv.org%2Fpdf%2F1403.6034&hl=pl&sa=T&oi=gga&ct=gga&cd=0&ei=0jIpVevHGtGcqwGlkoGgDw&scisig=AAGBfm0uNEheYuRR6NWYnpWbAGhwxnQ9eg&nossl=1&ws=1370x656

**Comment by adolgovina** [comment]
Anastasiia Dolgovina

1)Functional separation of languages in the bilingual brain: a comparison of electrical stimulation language mapping in 25 bilingual patients and 117 monolingual control patients
http://thejns.org/doi/abs/10.3171/jns.2004.101.3.0449

2) Shared and separate systems in bilingual language processing: Converging evidence from eyetracking and brain imaging 
http://www.sciencedirect.com/science/article/pii/S0093934X02005357

**Comment by juliakrakowiak** [comment]
Julia Krakowiak

Brain activity boosts processes that promote neural connections
http://www.sciencedaily.com/releases/2015/04/150406144602.htm

Emotional processing deficits linked with white matter damage
http://www.sciencedaily.com/releases/2015/04/150408100659.htm

**Comment by aherodzinska** [comment]
Aleksandra Herodzinska 

I'm sorry for submitting the homework late! 
1. Short-term memory in Down syndrome: Applying the working memory model
   http://www.down-syndrome.org/reviews/110/ 

2.Impact of Breast Milk on Intelligence Quotient, Brain Size, and White Matter Development http://www.nature.com/pr/journal/v67/n4/full/pr201066a.html 

3.Drinking Moderately and Pregnancy, Effects on Child Development
http://pubs.niaaa.nih.gov/publications/arh23-1/25-30.pdf

**Comment by zzhenna** [comment]
Zhang Zhenna

My topic is mainly concerning about  menmory ( hippocampus)

```
1.a glimpse into 3d brain: how menmories form 
   http://www.sciencedaily.com/releases/2014/10/141006085122.htm

2. How the brain decides when to modify old menmories and when to crave the new menmories 
     http://www.sciencedaily.com/releases/2014/11/141106143705.htm
```
