### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by ioannisstam25** [mmagnuski/Biology-of-Brain-and-Behavior#8]
Ioannis Stamatelos

1)The neural correlates of justified and unjustified killing: An fMRI study: 
http://www.sciencedaily.com/releases/2015/04/150408100651.htm

2)Relationship between exploratory eye movements and brain
morphology in schizophrenia spectrum patients: 
http://web.b.ebscohost.com/ehost/pdfviewer/pdfviewer?vid=43&sid=e02150df-9e5e-46ac-9bf7-9d843e930b38%40sessionmgr111&hid=109

**Comment by mmagnuski** [comment]
Hey, it will be much clearer if you post this in the original thread - Homework - papers.
I might have not been clear enough on our last meeting - your homeworks should go into one issue (the one I created).

**Comment by mmagnuski** [comment]
Ah, good, you have posted there already.
