### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by JedrzejNowe** [mmagnuski/Biology-of-Brain-and-Behavior#9]
1) Planning and spatial working memory following frontal lobe lesions in man
http://owenlab.uwo.ca/pdf/1990-Owen-Neuropsychologia-PLANNING%20AND%20SPATIAL%20WORKING%20MEMORY%20FOLLOWING%20FRONTAL%20LOBE%20LESIONS%20IN%20MAN.pdf

2) Differential Contribution of Amygdala and Hippocampus to Cued and Contextual Fear Conditioning
http://www.morganparkcps.org/ourpages/auto/2011/4/5/50843958/PhillipsR1992a.pdf

**Comment by mmagnuski** [comment]
Hey, it will be much clearer if you post this in the original thread - Homework - papers.
I might have not been clear enough on our last meeting - your homeworks should go into one issue (the one I created).

**Comment by mmagnuski** [comment]
Ah, good, you have posted there already.
